services:
  # 프론트엔드
  frontend:
    image: registry.vanicommu.click/vani-express:latest
    container_name: node-frontend
    ports:
      - "3000:3000"
    networks:
      - private-net

  backend:
    image: registry.vanicommu.click/vani-springboot:latest
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - private-net
      - db-private-net
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: mysql:8.0
    container_name: community
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: community
    networks:
      - db-private-net
    volumes:
      - ./mysql-data:/var/lib/mysql # 데이터 영속성
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - db-private-net

  # 5. 포테이너 에이전트 (Public의 Server가 접속)
  agent:
    image: portainer/agent:2.19.4
    container_name: portainer_agent
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - private-net

networks:
  private-net:
    driver: bridge
  db-private-net:
    driver: bridge
    internal: true
