spring:
  application:
    name: community-backend
  profiles:
    default: local

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/community?serverTimezone=Asia/Seoul&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    com.vani.week4.backend: debug

# === AWS S3
cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: vani-main-bucket
      auto: false

# === JWT: 시크릿과 토큰 만료 시간 설정
jwt:
  secret: ${JWT_SECRET}
  access-expiration-ms: 1800000
  refresh-expiration-ms: 1209600000
