# 부하 테스트용 설정
# 사용법: --spring.profiles.active=loadtest
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community_test?serverTimezone=UTC&useSSL=false
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    import: optional:file:.env[.properties]

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ture

server:
  # 톰캣이 X-Forwarded-* 헤더를 인식하게 설정
  forward-headers-strategy: framework

logging:
  level:
    root: INFO
    # 테스트 중인 좋아요 관련 로직만 상세히 관찰합니다.
    com.vani.week4.backend.interaction: DEBUG
    # 나머지 사용자 정의 코드는 INFO로 유지
    com.vani.week4.backend: INFO
    # 실행되는 SQL 쿼리를 확인해야 할 때만 DEBUG로 설정
    org.hibernate.SQL: DEBUG

jwt:
  secret: ${JWT_SECRET}
  access-expiration-ms: 1800000
  refresh-expiration-ms: 1209600000

# === AWS S3 (IAM Role 사용)
cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: vani-main-bucket
    stack:
      auto: false